      server:
        port: 8080
        servlet:
          context-path:

      spring:
        datasource:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql:///postgres
          username: postgres
          password: bounty
          hikari:
            data-source-properties:
              socketFactory: com.google.cloud.sql.postgres.SocketFactory
              cloudSqlInstance: urlshortner-421310:us-central1:bounty2

        jpa:
          hibernate:
            ddl-auto: create-drop
          properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
